// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using FimSync_Ezma.MovieJsonTypes;

namespace FimSync_Ezma.MovieJsonTypes
{

    internal class SpokenLanguage
    {

        [JsonProperty("iso_639_1")]
        public string iso_639_1 { get; set; }

        [JsonProperty("name")]
        public string name { get; set; }
    }

}
