// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FimSync_Ezma
{

    internal class Person
    {

        [JsonProperty("birthday")]
        public string birthday { get; set; }

        [JsonProperty("deathday")]
        public object deathday { get; set; }

        [JsonProperty("id")]
        public int id { get; set; }

        [JsonProperty("name")]
        public string name { get; set; }

        [JsonProperty("also_known_as")]
        public string[] also_known_as { get; set; }

        [JsonProperty("gender")]
        public int gender { get; set; }

        [JsonProperty("biography")]
        public string biography { get; set; }

        [JsonProperty("popularity")]
        public double popularity { get; set; }

        [JsonProperty("place_of_birth")]
        public string place_of_birth { get; set; }

        [JsonProperty("profile_path")]
        public string profile_path { get; set; }

        [JsonProperty("adult")]
        public bool adult { get; set; }

        [JsonProperty("imdb_id")]
        public string imdb_id { get; set; }

        [JsonProperty("homepage")]
        public string homepage { get; set; }

        [JsonProperty("known_for_department")]
        public string known_for_department { get; set; }
    }

}
